[build]
  publish = "_site/"
  command = "npm run build:pwa"
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3153600"
Referrer-Policy = "same-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=3153600"
